In [1]:
import os
import numpy as np
import pandas as pd
import librosa
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [4]:
output_path = '/Users/danielpark/Documents/DataScience/Datascience_final/dft_features.csv'
data =pd.read_csv(output_path)

In [ ]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(features_scaled, data['Genre'], test_size=0.2, random_state=42)

In [5]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Encoding the target variable if it's categorical
encoder = LabelEncoder()
data['Genre'] = encoder.fit_transform(data['Genre'])

# Scaling features
scaler = StandardScaler()
features = data.drop('Genre', axis=1)  # Assuming 'Genre' is the target
features_scaled = scaler.fit_transform(features)


In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_scaled, data['Genre'], test_size=0.2, random_state=42)

In [7]:
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV

# Initialize the RidgeClassifier
model = RidgeClassifier()

# Define the parameter grid
param_grid = {
    'alpha': [1, 10, 100], # Regularization strength
    'max_iter': [None, 100, 500],  # Maximum iterations
    'tol': [0.001, 0.01],  # Tolerance for stopping criteria
    'class_weight': [None, 'balanced']  # Handling imbalanced classes
}

# Setup the GridSearchCV
grid_search = GridSearchCV(model, param_grid, cv=3, scoring='accuracy')

# Fit GridSearchCV
grid_search.fit(X_train, y_train)

# Best model
print("Best parameters:", grid_search.best_params_)
print("Best cross-validation accuracy:", grid_search.best_score_)

# Evaluate on the test set
y_pred = grid_search.predict(X_test)
model.fit(X_train,y_train)


Best parameters: {'alpha': 100, 'class_weight': 'balanced', 'max_iter': None, 'tol': 0.001}
Best cross-validation accuracy: 0.41094629180779046


RidgeClassifier()

In [8]:
from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)


Accuracy: 0.3964978111319575
Confusion Matrix:
 [[ 58  14  13  39  23  19  16  10]
 [ 10  34  22  14  41  33  10  22]
 [  2  10  86   2  59  16  11   7]
 [ 41  17   5 107  16  17  12  14]
 [  4  11  26   5 124   4   7   7]
 [ 15  13  28  19  29 101   8  12]
 [ 20  16  23  17  18  35  28  20]
 [  8  10  21  14  31  11  18  96]]
